# Generated by Django 5.0 on 2023-12-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Moeda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=3, verbose_name="Sigla")),
                ("moeda", models.CharField(max_length=50, verbose_name="Moeda")),
                ("bandeira", models.ImageField(upload_to="bandeiras")),
            ],
            options={
                "verbose_name": "Moeda",
                "verbose_name_plural": "Moedas",
            },
        ),
    ]
